routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('shares', 'ShareController');

Route::resource('/products', 'ProductController');

Route::resource('/customers', 'CustomerController');

Route::resource('/order', 'OrderController');

Route::resource('/adminlte', 'AdminLteController');

Route::resource('ajax-crud', 'AjaxController');


Route::get('manage-item-ajax', 'ArtikelController@manageItemAjax');
Route::resource('item-ajax', 'ArtikelController');

// new routes

Route::resource('/links', 'LinkController');




//--CREATE a link--//
// Route::post('/links', function (Request $request) {
//     $link = Link::create($request->all());
//     return Response::json($link);
// });

// //--GET LINK TO EDIT--//
// Route::get('/links/{link_id?}', function ($link_id) {
//     $link = Link::find($link_id);
//     return Response::json($link);
// });

// //--UPDATE a link--//
// Route::put('/links/{link_id?}', function (Request $request, $link_id) {
//     $link = Link::find($link_id);
//     $link->url = $request->url;
//     $link->description = $request->description;
//     $link->save();
//     return Response::json($link);
// });

//--DELETE a link--//
// Route::delete('/links/{link_id?}', function ($link_id) {
//     $link = Link::destroy($link_id);
//     return Response::json($link);
// });

app/Share.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Share extends Model
{
  protected $table = "shares";
  protected $fillable = ['share_name', 'share_price', 'share_qty'];
  protected $guarded = [];
}

app/Http/Controllers/ShareController.php
<?php

namespace App\Http\Controllers;

use App\Share;
use Illuminate\Http\Request;

class ShareController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $share = Share::all();

        return response()->json($share);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('shares.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Share  $share
     * @return \Illuminate\Http\Response
     */
    public function show(Share $share)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Share  $share
     * @return \Illuminate\Http\Response
     */
    public function edit(Share $share)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Share  $share
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Share $share)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Share  $share
     * @return \Illuminate\Http\Response
     */
    public function destroy(Share $share)
    {
        //
    }
}

resources/views/shares/create.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('shares.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Share Name:</label>
              <input type="text" class="form-control" name="share_name"/>
          </div>
          <div class="form-group">
              <label for="price">Share Price :</label>
              <input type="text" class="form-control" name="share_price"/>
          </div>
          <div class="form-group">
              <label for="quantity">Share Quantity:</label>
              <input type="text" class="form-control" name="share_qty"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@endsection